// src: 原图（viewer.html 大图查看用）；thumb: 压缩缩略图（index.html 瀑布流用）；width/height: 自动生成的真实尺寸
const images = [
  {
    src: "resume-awards/imgs/0004-字节工训营.JPG",
    thumb: "resume-awards/imgs/thumbs/0004-字节工训营.jpg",
    alt: "字节工训营",
    width: 2772,
    height: 2056,
    thumbWidth: 900,
    thumbHeight: 649,
  },
  {
    src: "resume-awards/imgs/腾讯青科实训营.png",
    thumb: "resume-awards/imgs/thumbs/腾讯青科实训营.jpg",
    alt: "腾讯青科实训营",
    width: 4960,
    height: 7016,
    thumbWidth: 636,
    thumbHeight: 900,
  },
  {
    src: "resume-awards/imgs/0003-腾讯开源.jpg",
    thumb: "resume-awards/imgs/thumbs/0003-腾讯开源.jpg",
    alt: "腾讯开源",
    width: 1179,
    height: 1786,
    thumbWidth: 594,
    thumbHeight: 900,
  },
  {
    src: "resume-awards/imgs/0010-百度之星.JPG",
    thumb: "resume-awards/imgs/thumbs/0010-百度之星.jpg",
    alt: "百度之星",
    width: 1811,
    height: 1280,
    thumbWidth: 900,
    thumbHeight: 636,
  },
  {
    src: "resume-awards/imgs/0013-Datawhale-Agent.JPG",
    thumb: "resume-awards/imgs/thumbs/0013-Datawhale-Agent.jpg",
    alt: "Datawhale-Agent",
    width: 1280,
    height: 904,
    thumbWidth: 900,
    thumbHeight: 635,
  },
  {
    src: "resume-awards/imgs/0001-天梯赛.PNG",
    thumb: "resume-awards/imgs/thumbs/0001-天梯赛.jpg",
    alt: "天梯赛",
    width: 788,
    height: 1112,
    thumbWidth: 637,
    thumbHeight: 900,
  },
  {
    src: "resume-awards/imgs/0002-睿抗.JPG",
    thumb: "resume-awards/imgs/thumbs/0002-睿抗.jpg",
    alt: "睿抗",
    width: 1000,
    height: 707,
    thumbWidth: 900,
    thumbHeight: 636,
  },
  {
    src: "resume-awards/imgs/0011-码蹄杯.JPG",
    thumb: "resume-awards/imgs/thumbs/0011-码蹄杯.jpg",
    alt: "码蹄杯",
    width: 904,
    height: 1280,
    thumbWidth: 635,
    thumbHeight: 900,
  },
  {
    src: "resume-awards/imgs/0101-美国大学生数学建模大赛.jpg",
    thumb: "resume-awards/imgs/thumbs/0101-美国大学生数学建模大赛.jpg",
    alt: "美国大学生数学建模大赛",
    width: 1179,
    height: 867,
    thumbWidth: 900,
    thumbHeight: 662,
  },
  {
    src: "resume-awards/imgs/1001-上大-优秀学生.jpg",
    thumb: "resume-awards/imgs/thumbs/1001-上大-优秀学生.jpg",
    alt: "优秀学生",
    width: 1850,
    height: 1279,
    thumbWidth: 900,
    thumbHeight: 622,
  },
  {
    src: "resume-awards/imgs/1002-上大公益奖学金.JPG",
    thumb: "resume-awards/imgs/thumbs/1002-上大公益奖学金.jpg",
    alt: "公益奖学金",
    width: 3264,
    height: 2272,
    thumbWidth: 900,
    thumbHeight: 626,
  },
  {
    src: "resume-awards/imgs/1003-上大科创奖学金.JPG",
    thumb: "resume-awards/imgs/thumbs/1003-上大科创奖学金.jpg",
    alt: "科创奖学金",
    width: 3264,
    height: 2312,
    thumbWidth: 900,
    thumbHeight: 637,
  },
  {
    src: "resume-awards/imgs/1004-上大科创奖学金2.JPG",
    thumb: "resume-awards/imgs/thumbs/1004-上大科创奖学金2.jpg",
    alt: "科创奖学金2",
    width: 2592,
    height: 1860,
    thumbWidth: 900,
    thumbHeight: 646,
  },
  {
    src: "resume-awards/imgs/1005-企创大赛特等奖.jpg",
    thumb: "resume-awards/imgs/thumbs/1005-企创大赛特等奖.jpg",
    alt: "企创大赛特等奖",
    width: 4032,
    height: 2389,
    thumbWidth: 900,
    thumbHeight: 533,
  },
  {
    src: "resume-awards/imgs/中国计算机协会CSP证书.png",
    thumb: "resume-awards/imgs/thumbs/中国计算机协会CSP证书.jpg",
    alt: "中国计算机协会CSP证书",
    width: 1410,
    height: 1825,
    thumbWidth: 695,
    thumbHeight: 900,
  },
];
