name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天凌晨执行
  workflow_dispatch:      # 手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ceilf6
          svg_out_path: dist/github-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
