name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # 每天自动运行一次
  workflow_dispatch:     # 支持手动运行

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: ceilf6
          outputs: dist  # ⚠️ 注意：只写 dist，不要加 svg?raw=true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
